# Generated by Django 3.1.7 on 2021-03-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_information',
            field=models.CharField(default=2, max_length=50, verbose_name='Порция и вес'),
            preserve_default=False,
        ),
    ]
