# Generated by Django 3.1.7 on 2021-03-03 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_reviewproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('person', models.IntegerField()),
                ('payment', models.CharField(choices=[('in_cash', 'Наличными при получении'), ('credit_card', 'Оплата банковской картой при получении')], default='credit_card', max_length=100, verbose_name='Тип оплаты')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('postponed', 'Отложен'), ('ready_for_delivery', 'Готов к доставке'), ('picked_up_by_courier', 'Взят курьером'), ('delivered', 'Доставляется'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='new', max_length=100, verbose_name='Статус заказа')),
                ('branch', models.CharField(choices=[('vefa', 'Вефа'), ('asia_mall', 'Азия молл'), ('tsum', 'Цум'), ('bishkek_park', 'Бишкек парк')], default='vefa', max_length=100, verbose_name='Филиалы')),
                ('delivery_type', models.CharField(choices=[('self', 'Самовывоз'), ('delivery', 'Доставка')], default='self', max_length=100, verbose_name='Тип заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения заказа')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира')),
                ('entrance', models.CharField(blank=True, max_length=50, null=True, verbose_name='Подъезд')),
                ('intercom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Домофон')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField(default=1)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product')),
            ],
        ),
    ]
