# Generated by Django 3.1.7 on 2021-03-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_cartitem_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=12, verbose_name='Общая цена'),
            preserve_default=False,
        ),
    ]
