# Generated by Django 3.1.7 on 2021-03-05 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210304_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='order.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='person',
            field=models.IntegerField(verbose_name='Сколько персон'),
        ),
    ]
