# Generated by Django 3.1.7 on 2021-03-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210305_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.CharField(choices=[('vefa', 'Вефа'), ('Азия молл', 'Азия молл'), ('tsum', 'Цум'), ('bishkek_park', 'Бишкек парк')], default='vefa', max_length=100, verbose_name='Филиалы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('self', 'Самовывоз'), ('Доставка', 'Доставка')], default='self', max_length=100, verbose_name='Тип заказа'),
        ),
    ]
