# Generated by Django 3.1.7 on 2021-03-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210305_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.CharField(choices=[('vefa', 'Вефа'), ('Азия молл', 'Азия молл'), ('tsum', 'Цум'), ('Бишкек парк', 'Бишкек парк')], default='vefa', max_length=100, verbose_name='Филиалы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Самовывоз', max_length=100, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('Заказ в обработке', 'Заказ в обработке'), ('postponed', 'Отложен'), ('Готов к доставке', 'Готов к доставке'), ('picked_up_by_courier', 'Взят курьером'), ('delivered', 'Доставляется'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='Заказ в обработке', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
