# Generated by Django 3.1.7 on 2021-03-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210305_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.CharField(choices=[('Вефа', 'Вефа'), ('Азия молл', 'Азия молл'), ('Цум', 'Цум'), ('Бишкек парк', 'Бишкек парк')], default='Вефа', max_length=100, verbose_name='Филиалы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Наличными при получении', 'Наличными при получении'), ('Оплата банковской картой при получении', 'Оплата банковской картой при получении')], default='Оплата банковской картой при получении', max_length=100, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый заказ', 'Новый заказ'), ('Заказ в обработке', 'Заказ в обработке'), ('Отложен', 'Отложен'), ('Готов к доставке', 'Готов к доставке'), ('Взят курьером', 'Взят курьером'), ('Доставляется', 'Доставляется'), ('Выполнен', 'Выполнен'), ('Отменен', 'Отменен')], default='Заказ в обработке', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
